### ISSUE TITLE
Error on BitcoinInterest

### ISSUE THREAD

**Issue by cdarken** [AndreaLanfranchi/ethminer#45]
Out of curiosity I tried to use your miner for BCI, but I get this error:

```
Got ProgPoW job with missing block number. Discarding ...
```
The cmd line is:
```
ethminer -G --HWMON 1 -P stratum+tcp://cdarken.RX:x@bci.suprnova.cc:9166 -A progpow
```
Message from the server:
```
 << {"id":null,"method":"mining.notify","params":["000000000000000000000000000000000000000000000000000000000000e657","486afc1ddd865499f8f6e988ba19005f6bfa135df27599d770525b4355021d10","582b06447f087674bcc0a32a19961e77dafb9e17955792f79ec8936e3d9742fc","0000007ffff80000000000000000000000000000000000000000000000000000",true]}
```
Their fork of ethminer seems to work fine on two pools I've tried, this one and the official one, pool.bitcoininterest.io.

**Comment by AndreaLanfranchi** [comment]
@cdarken this miner is for the ethereum (and ethash derivative) mining.
It can't work on Bitcoin Interest.

**Comment by cdarken** [comment]
Maybe I understood wrong. Wasn't progpow an "universal" mining algorithm meant to replace ethash? Is your implementation ethereum specific?

**Comment by AndreaLanfranchi** [comment]
Yes it is ... but there is a difference : progpow from BCI (I'm looking at their repo right now) is implemented to change when ethash epoch changes. Our, instead, rebuilds the kernel every 50 blocks (i.e. every 12.5 minutes roughly) thus we need the mining pool to push the candidate block number.

**Comment by AndreaLanfranchi** [comment]
We could easily adapt ethminer to implement also the same behavior but, as far as I can see from their progminer they're behind from latest ifdefelse's specs so, I have to assume, our eventually found nonces won't fit into checks by their nodes.

**Comment by cdarken** [comment]
Oh, ok. Then something changed since they forked and they implemented progpow. That explains it.
